name: Rebuild on Change

on:
  push:
    branches:
      - "**" # All branches
  pull_request:
    branches:
      - "**" # Optional: PRs too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (if using JS/React/etc)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
